core/urls.py
from django.conf.urls import url
from .views import *
#url for app

app_name = "core"
urlpatterns = [
    url(r'^$', index, name='index'),
    url(r'^predict/$', predict, name='predict'),
    url(r'^score/$', score, name='score'),
]

sentiment_analysis/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
]

core/models.py
from django.db import models

POSITIVE = "positif"
NEGATIVE = "negatif"
NEUTRAL = "netral"

SENTIMENT = (
    (POSITIVE, "positif"),
    (NEGATIVE, "negatif"),
    (NEUTRAL, "netral")
)

# Create your models here.
class Word(models.Model):
    word = models.CharField(max_length=140)
    sentiment = models.CharField(choices=SENTIMENT, max_length=8, default=NEUTRAL)

    def __str__(self):
        return self.word + " (" + self.sentiment + ")"

core/forms.py
from django import forms

# Tweet Form
class TweetForm(forms.Form):
    tweet = forms.CharField(widget = forms.Textarea, label='Your tweet', max_length=140)

core/views.py
from django.shortcuts import render
from .sentiment import *
from .models import *
import string


# Create your views here.
def index(request):
    response = {"last_five": Word.objects.all().order_by('-id')[:5]}
    print(response)
    return render(request, 'index.html', response)

def predict(request):
    response = {"last_five": Word.objects.all().order_by('-id')[:5]}
    sentimentChecker = Sentiment()
    if request.method == 'POST':
        tweet = request.POST['tweet']
        if tweet != '':
            response.update({'tweet': tweet})
            result = sentimentChecker.categorize(tweet)
            if (result == 'positif'):
                response.update({'result': 'positif'})
            elif (result == 'negatif'):
                response.update({'result': 'negatif'})
            elif (result == 'netral'):
                response.update({'result': 'netral'})
            listKata = sentimentChecker.listKata
            klasifikasikata = {}

            cleartweet = ""
            for char in tweet:
                if char not in string.punctuation:
                    cleartweet += char

            for kata in cleartweet.split(' '):
                if kata.lower() in listKata:
                    klasifikasikata.update({kata: listKata[kata.lower()]})
            response.update({'klasifikasi': klasifikasikata})

    return render(request, 'index.html', response)

def score(request):
    response = {"last_five": Word.objects.all().order_by('-id')[:5]}
    sentimentChecker = Sentiment()
    if request.method == 'POST':
        word = request.POST['word']
        sentiment = request.POST['sentiment']
        new_word = Word.objects.create(word=word, sentiment=sentiment)

        tweet = request.POST['tweet']
        if tweet != '':
            response.update({'tweet': tweet})
            result = sentimentChecker.categorize(tweet)
            if (result == 'positif'):
                response.update({'result': 'positif'})
            elif (result == 'negatif'):
                response.update({'result': 'negatif'})
            elif (result == 'netral'):
                response.update({'result': 'netral'})
            listKata = sentimentChecker.listKata
            klasifikasikata = {}

            cleartweet = ""
            for char in tweet:
                if char not in string.punctuation:
                    cleartweet += char

            for kata in cleartweet.split(' '):
                if kata.lower() in listKata:
                    klasifikasikata.update({kata: listKata[kata.lower()]})
            response.update({'klasifikasi': klasifikasikata})

    return render(request, 'index.html', response)

core/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="{% static 'index.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
	<title>Probabilistic Review</title>
</head>
<body>
<div class="full">
    <div class="jumbotron" style="padding: 2rem 1rem;">
    <div class="container">
        <h1 class="display-4">Sentiment Analysis</h1>
        <p>Menggunakan probabilistic learning, yang didasari teori Bayes, kami menganalisa nilai emosi yang terkandung dalam dalam sebuah teks Bahasa Indonesia.</p>
    </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <h2>Analyze Sentiment</h2>
            <p class="lead">Input</p>
                <form class="tweet-form" action="{% url 'core:predict' %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>Your tweet:</label>
                        <textarea class="form-control tweet-text" name="tweet" rows="5"></textarea>
                    </div>
                    <script>
                        $(".tweet-text").keydown(function(event) {
                            if (event.keyCode === 13) {
                                $("#tombol").click();
                                event.preventDefault()
                            }
                        });
                    </script>

                    <!-- {{ form }} -->
                    <button id="tombol" class="btn btn-primary">Analyze Tweet</button>
                </form>
        </div>
        <div class="col-md-6">
            <h2>Analysis Result</h2>
            <p class="lead">Output</p>
            {% if tweet %}
            <label>Your tweet:</label>
            <div class="card p-1">
                <blockquote class="blockquote mb-0 card-body">
                {% for kata, klas in klasifikasi.items %}
                    {% if klas == 'positif' %}
                    <p class="kata kata-positif" style="color: green;">{{ kata }}</p>
                    {% elif klas == 'negatif' %}
                    <p class="kata kata-negatif" style="color: red;">{{ kata }}</p>
                    {% elif klas == 'netral' %}
                    <p class="kata kata-netral">{{ kata }}</p>
                    {% elif klas == 'ignore' %}
                    <p class="kata kata-ignore" style="color: grey;">{{ kata }}</p>
                    {% else %}
                    <a data-toggle="modal" data-target="#exampleModal" data-kata="{{ kata }}">
                    <p class="kata kata-unknown" style="background-color: #f6f6f6;">{{ kata }}</p>
                    </a>
                    {% endif %}
                {% endfor %}
                <footer class="blockquote-footer">
                    <small class="text-muted">
                        You
                    </small>
                </footer>
                </blockquote>
            </div>
            {% endif %}
            {% if result == 'positif' %}
            <p class="tweet-positif">The tweet is positive</p>
            {% elif result == 'negatif' %}
            <p class="tweet-negatif">The tweet is negative</p>
            {% elif result == 'netral' %}
            <p class="tweet-netral">The tweet is neutral</p>
            {% endif %}

            <!-- Modal -->

            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Skor nilai</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <form action="{% url 'core:score' %}" method="post"> {% csrf_token %}
                      <div class="form-group">
                        <input type="hidden" name="tweet" value="{{ tweet }}">
                      </div>

                      <div class="form-group">
                        <label for="wordInput">Kata</label>
                        <input type="text" name="word" id="wordInput" class="form-control" readonly>
                      </div>

                      <div class="form-group">
                        <label>Sentimen</label>
                        <div class="form-check">
                          <input class="form-check-input" type="radio" name="sentiment" id="radio1" value="positif" checked>
                          <label class="form-check-label" for="radio1">
                            Positif
                          </label>
                        </div>

                        <div class="form-check">
                          <input class="form-check-input" type="radio" name="sentiment" id="radio2" value="netral">
                          <label class="form-check-label" for="radio2">
                            Netral
                          </label>
                        </div>
                        <div class="form-check">
                          <input class="form-check-input" type="radio" name="sentiment" id="radio3" value="negatif">
                          <label class="form-check-label" for="radio3">
                            Negatif
                          </label>
                        </div>
                      </div>

                      <button class="btn btn-primary">Submit</button>
                    </form>
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <div class="row mt-3"></div>
    <div class="row">
      <div class="col-md-3">
        <!-- Test -->
      </div>
      <div class="col-md-6">
        <div class="container">
          <p class="lead">Recent Contributions</p>
          <table class="table">
            <thead>
              <tr>
                <th scope="col">Kata</th>
                <th scope="col">Sentimen</th>
              </tr>
            </thead>
            <tbody>
              {% for i in last_five %}
              <tr>
                <td>{{ i.word }}</td>
                <td>{{ i.sentiment }}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
    <div class="container mt-1"></div>
    <footer class="container">
        <p>Made with ❤️ by Ahmad Satryaji Aulia, Azhar Kurnia, Kianutama Radianur</p>
    </footer>
</div>
<script>
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var kata = button.data('kata') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('Skor nilai dari \"' + kata + '\"')
  modal.find('.modal-body #wordInput').val(kata)
})
</script>
</body>
</html>